SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS DS_WEBSSO_USER;
CREATE TABLE DS_WEBSSO_USER (
  ID bigint(20) NOT NULL COMMENT '主键',
  IDCARD varchar(18) DEFAULT NULL COMMENT '身份证号',
  USERACCOUNT varchar(60) DEFAULT NULL COMMENT '用户账号',
  SSOACCOUNT varchar(60) DEFAULT NULL COMMENT 'sso账号',
  CITY varchar(60) DEFAULT NULL COMMENT '城市',
  COUNTRY varchar(60) DEFAULT NULL COMMENT '国家',
  PROVINCE varchar(60) DEFAULT NULL COMMENT '省份',
  NAME varchar(30) DEFAULT NULL COMMENT '姓名',
  SEX int(1) DEFAULT NULL COMMENT '性别(0未知,1男,2女)',
  EMAIL varchar(300) DEFAULT NULL COMMENT '电子邮件',
  MOBILE varchar(30) DEFAULT NULL COMMENT '手机',
  PHONE varchar(30) DEFAULT NULL COMMENT '电话',
  AVATAR varchar(300) DEFAULT NULL COMMENT '头像',
  OPENIDQQ varchar(300) DEFAULT NULL COMMENT 'qq登陆的openid',
  OPENIDALIPAY varchar(300) DEFAULT NULL COMMENT '支付宝登陆的openid',
  OPENIDWECHAT varchar(300) DEFAULT NULL COMMENT '微信登陆的openid',
  PRIMARY KEY (ID)
) COMMENT '用户账号';

