package dswork.android.demo.framework.app.greendao.dao;

import dswork.android.lib.db.BaseModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PERSON.
 */
public class Person extends BaseModel{

    private Long id;
    private String name;
    private String phone;
    private String amount;
    private String sortkey;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String name, String phone, String amount, String sortkey) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.amount = amount;
        this.sortkey = sortkey;
    }
    
    public Person(String name, String phone, String amount) {
    	this.name = name;
    	this.phone = phone;
    	this.amount = amount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getSortkey() {
        return sortkey;
    }

    public void setSortkey(String sortkey) {
        this.sortkey = sortkey;
    }

}
